In [ ]:
print("HELO")

HELO


In [ ]:
pip install lab-utils

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 kB 3.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Created wheel for lab-utils: filename=lab_utils-0.5.12-py3-none-any.whl size=37981 sha256=196722ac297831d2fc68ec4461a7bb4706717374eda2fcc6cf2cb0be7e100751
  Stored in directory: /root/.cache/pip/wheels/26/77/f2/0f8dcc372e550c877a72b782bd31bef99e7eac01f30a4f99fe
  Created wheel for slacker-log-handler: filename=slacker_log_handler-1.8.0-py2.py3-none-any.whl size=8402 sha256=53ec87d45e9d3de1bb1e9aace325ab846d0f561b10a693c00fbc7ea83d862061
  Stored in directory: /root/.cache/pip/wheels/c3/6b/54/66519553e4466153d58fe9296379564db8594e5e875fdbcc3f
  Created wheel for slacker: filename=slacker-0.9.65-py3-none-any.whl size=7743 sha256=f53392fd73dc9b8f314cb033da918c0550a8505d7d63e07f783c6b309b0cf8fd
 

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving lab_utils_common.py to lab_utils_common.py
Saving lab_utils_multi.py to lab_utils_multi.py


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import SGDRegressor
from sklearn.preprocessing import StandardScaler
from lab_utils_multi import  load_house_data
from lab_utils_common import dlc
np.set_printoptions(precision=2)
plt.style.use('./deeplearning.mplstyle')
print("Sucksexfull")



Sucksexfull


In [ ]:
import pandas as pd
df = pd.read_csv('Real estate.csv')
print(df)

      No  X1 transaction date  X2 house age  \
0      1             2012.917          32.0   
1      2             2012.917          19.5   
2      3             2013.583          13.3   
3      4             2013.500          13.3   
4      5             2012.833           5.0   
..   ...                  ...           ...   
409  410             2013.000          13.7   
410  411             2012.667           5.6   
411  412             2013.250          18.8   
412  413             2013.000           8.1   
413  414             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 3

In [ ]:
import pandas as pd
df = pd.read_csv('Real estate.csv')
print(df)

      No  X1 transaction date  X2 house age  \
0      1             2012.917          32.0   
1      2             2012.917          19.5   
2      3             2013.583          13.3   
3      4             2013.500          13.3   
4      5             2012.833           5.0   
..   ...                  ...           ...   
409  410             2013.000          13.7   
410  411             2012.667           5.6   
411  412             2013.250          18.8   
412  413             2013.000           8.1   
413  414             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 3

In [ ]:
print(df.values[1])

[2.00e+00 2.01e+03 1.95e+01 3.07e+02 9.00e+00 2.50e+01 1.22e+02 4.22e+01]


In [ ]:
print(df.columns[7])

Y house price of unit area


In [ ]:
y_train = df['Y house price of unit area'].values
print(y_train)

[ 37.9  42.2  47.3  54.8  43.1  32.1  40.3  46.7  18.8  22.1  41.4  58.1
  39.3  23.8  34.3  50.5  70.1  37.4  42.3  47.7  29.3  51.6  24.6  47.9
  38.8  27.   56.2  33.6  47.   57.1  22.1  25.   34.2  49.3  55.1  27.3
  22.9  25.3  47.7  46.2  15.9  18.2  34.7  34.1  53.9  38.3  42.   61.5
  13.4  13.2  44.2  20.7  27.   38.9  51.7  13.7  41.9  53.5  22.6  42.4
  21.3  63.2  27.7  55.   25.3  44.3  50.7  56.8  36.2  42.   59.   40.8
  36.3  20.   54.4  29.5  36.8  25.6  29.8  26.5  40.3  36.8  48.1  17.7
  43.7  50.8  27.   18.3  48.   25.3  45.4  43.2  21.8  16.1  41.   51.8
  59.5  34.6  51.   62.2  38.2  32.9  54.4  45.7  30.5  71.   47.1  26.6
  34.1  28.4  51.6  39.4  23.1   7.6  53.3  46.4  12.2  13.   30.6  59.6
  31.3  48.   32.5  45.5  57.4  48.6  62.9  55.   60.7  41.   37.5  30.7
  37.5  39.5  42.2  20.8  46.8  47.4  43.5  42.5  51.4  28.9  37.5  40.1
  28.4  45.5  52.2  43.2  45.1  39.7  48.5  44.7  28.9  40.9  20.7  15.6
  18.3  35.6  39.4  37.4  57.8  39.6  11.6  55.5  5

In [ ]:
import numpy as np
df2 = df.drop(df.columns[7],axis = 1)
x_train = ([])
for i in range(414):
  x_train = np.append(x_train, df2.values[i])
print(x_train.reshape(414,7))

[[1.00e+00 2.01e+03 3.20e+01 ... 1.00e+01 2.50e+01 1.22e+02]
 [2.00e+00 2.01e+03 1.95e+01 ... 9.00e+00 2.50e+01 1.22e+02]
 [3.00e+00 2.01e+03 1.33e+01 ... 5.00e+00 2.50e+01 1.22e+02]
 ...
 [4.12e+02 2.01e+03 1.88e+01 ... 7.00e+00 2.50e+01 1.22e+02]
 [4.13e+02 2.01e+03 8.10e+00 ... 5.00e+00 2.50e+01 1.22e+02]
 [4.14e+02 2.01e+03 6.50e+00 ... 9.00e+00 2.50e+01 1.22e+02]]


In [ ]:
x_train = x_train.reshape(414,7)
import matplotlib.pyplot as plt
from sklearn.linear_model import SGDRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from lab_utils_multi import  load_house_data
from lab_utils_common import dlc
np.set_printoptions(precision=2)
plt.style.use('./deeplearning.mplstyle')
scaler = StandardScaler()
x_norm = scaler.fit_transform(x_train)
print(f"Peak to Peak range by column in Raw        X:{np.ptp(x_train,axis=0)}")
print(f"Peak to Peak range by column in Normalized X:{np.ptp(x_norm,axis=0)}")

Peak to Peak range by column in Raw        X:[4.13e+02 9.16e-01 4.38e+01 6.46e+03 1.00e+01 8.25e-02 9.27e-02]
Peak to Peak range by column in Normalized X:[3.46 3.25 3.85 5.13 3.4  6.66 6.05]


In [ ]:
sgdr = SGDRegressor(max_iter=1000)
sgdr.fit(x_norm, y_train)
print(sgdr)
print(f"number of iterations completed: {sgdr.n_iter_}, number of weight updates: {sgdr.t_}")

SGDRegressor()
number of iterations completed: 25, number of weight updates: 10351.0


In [ ]:
b_norm = sgdr.intercept_
w_norm = sgdr.coef_
print(f"model parameters:                   w: {w_norm}, b:{b_norm}")

model parameters:                   w: [-0.42  1.38 -3.09 -5.33  3.37  2.84 -0.01], b:[37.95]


In [ ]:
y_pred_sgd = sgdr.predict(x_norm)
y_pred = np.dot(x_norm, w_norm) + b_norm
print(f"prediction using np.dot() and sgdr.predict match: {(y_pred == y_pred_sgd).all()}")

print(f"Prediction on training set:\n{y_pred[:10]}" )
print(f"Target values \n{y_train[:10]}")
r2 = r2_score(y_train, y_pred)
print('r2 score for model is', r2)

prediction using np.dot() and sgdr.predict match: True
Prediction on training set:
[47.85 48.56 49.47 49.06 46.91 31.96 39.37 47.43 10.19 35.32]
Target values 
[37.9 42.2 47.3 54.8 43.1 32.1 40.3 46.7 18.8 22.1]
r2 score for model is 0.5831669587005699


Now applying linear regression from scratch

In [ ]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('./deeplearning.mplstyle')
np.set_printoptions(precision=2)  # reduced display precision on numpy arrays
def compute_gradient(X, y, w, b):
    m,n = X.shape           #(number of examples, number of features)
    dj_dw = np.zeros((n,))
    dj_db = 0.

    for i in range(m):
        err = (np.dot(X[i], w) + b) - y[i]
        for j in range(n):
            dj_dw[j] = dj_dw[j] + err * X[i, j]
        dj_db = dj_db + err
    dj_dw = dj_dw / m
    dj_db = dj_db / m

    return dj_db, dj_dw

In [ ]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('./deeplearning.mplstyle')
np.set_printoptions(precision=2)  # reduced display precision on numpy arrays
def gradient_descent(X, y, w_in, b_in, cost_function, gradient_function, alpha, num_iters):

    # An array to store cost J and w's at each iteration primarily for graphing later
    J_history = []
    w = copy.deepcopy(w_in)  #avoid modifying global w within function
    b = b_in

    for i in range(num_iters):

        # Calculate the gradient and update the parameters
        dj_db,dj_dw = gradient_function(X, y, w, b)   ##None

        # Update Parameters using w, b, alpha and gradient
        w = w - alpha * dj_dw               ##None
        b = b - alpha * dj_db               ##None

        # Save cost J at each iteration
        if i<100000:      # prevent resource exhaustion
            J_history.append( cost_function(X, y, w, b))

        # Print cost every at intervals 10 times or as many iterations if < 10
        if i% math.ceil(num_iters / 10) == 0:
            print(f"Iteration {i:4d}: Cost {J_history[-1]:8.2f}   ")

    return w, b, J_history #return final w,b and J history for graphing

In [ ]:
def predict(x, w, b):
    p = np.dot(x, w) + b
    return p

In [ ]:
def compute_cost(X, y, w, b):
    m = X.shape[0]
    cost = 0.0
    for i in range(m):
        f_wb_i = np.dot(X[i], w) + b           #(n,)(n,) = scalar (see np.dot)
        cost = cost + (f_wb_i - y[i])**2       #scalar
    cost = cost / (2 * m)                      #scalar
    return cost

In [ ]:
# initialize parameters
initial_w = np.zeros_like(x_train[0])
initial_b = 0.
# some gradient descent settings
iterations = 6000
alpha = 5.0e-10
# run gradient descent
w_final, b_final, J_hist = gradient_descent(x_train, y_train, initial_w, initial_b,
                                                    compute_cost, compute_gradient,
                                                    alpha, iterations)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")
for i in range(10):
    print(f"prediction: {np.dot(x_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

Iteration    0: Cost   810.19   
Iteration  600: Cost   174.76   
Iteration 1200: Cost   105.02   
Iteration 1800: Cost    77.81   
Iteration 2400: Cost    64.33   
Iteration 3000: Cost    57.53   
Iteration 3600: Cost    54.10   
Iteration 4200: Cost    52.36   
Iteration 4800: Cost    51.49   
Iteration 5400: Cost    51.04   
b,w found by gradient descent: 0.00,[ 2.04e-03  2.21e-02  1.01e-04 -6.75e-03  9.10e-05  2.74e-04  1.33e-03] 
prediction: 44.08, target value: 37.9
prediction: 42.59, target value: 42.2
prediction: 40.88, target value: 47.3
prediction: 40.88, target value: 54.8
prediction: 42.02, target value: 43.1
prediction: 29.98, target value: 32.1
prediction: 40.45, target value: 40.3
prediction: 42.74, target value: 46.7
prediction: 7.48, target value: 18.8
prediction: 32.65, target value: 22.1


Applying the code from scratch without help

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import copy, math
plt.style.use('./deeplearning.mplstyle')
np.set_printoptions(precision=2)
df = pd.read_csv('Real estate.csv')
yt = df['Y house price of unit area'].values
xt = np.array([])
df2 = df.drop(df.columns[7],axis=1)
for i in range(414):
  xt = np.append(xt,df2.values[i])
xt = xt.reshape(414,7)

In [ ]:
class lreg():
  def __init__(self, xtrain, ytrain):
    self.xtrain = xtrain
    self.ytrain = ytrain
  def grad(self, w, b):
    a = self.xtrain
    b = self.ytrain
    m,n = a.shape
    djw = np.zeros(n,)
    djb = 0
    for i in range(m):
      err = (np.dot(w,a[i])+b) - b[i]
      for j in range(n):
        djw[j] = djw[j] + err*a[i,j]
      djb = djb + err
    djw = djw/m
    djb = djb/m
    return djw,djb
  def cost(self, w, b):
    a = self.xtrain
    c = self.ytrain
    m = a.shape[0]
    cost = 0.0
    for i in range(m):
        f_wb_i = np.dot(a[i], w) + b           #(n,)(n,) = scalar (see np.dot)
        cost = cost + (f_wb_i - c[i])**2       #scalar
    cost = cost / (2 * m)                      #scalar
    return cost
  def gdesc(self, win, bin, cost, grad, iter, alpha):
    J_history = []
    w = copy.deepcopy(win)
    b = bin
    a = self.xtrain
    c = self.ytrain
    dj_db,dj_dw = grad(a, c, w, b)
    for i in range(iter):
      w = w - alpha * dj_dw
      b = b - alpha * dj_db
      if i<100000:
          J_history.append( cost(X, y, w, b))
      if i% math.ceil(iter / 10) == 0:
            print(f"Iteration {i:4d}: Cost {J_history[-1]:8.2f}   ")
    return w, b, J_history

In [ ]:
l1 = lreg(xt,yt)
# initialize parameters
initial_w = np.zeros_like(xt[0])
initial_b = 0.
# some gradient descent settings
iterations = 6000
alpha = 5.0e-10
# run gradient descent
w_final, b_final, J_hist = l1.gdesc(initial_w, initial_b, l1.cost, l1.grad,iterations, alpha)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")
for i in range(10):
    print(f"prediction: {np.dot(xt[i], w_final) + b_final:0.2f}, target value: {yt[i]}")

TypeError: ignored

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import copy, math
plt.style.use('./deeplearning.mplstyle')
np.set_printoptions(precision=2)
df = pd.read_csv('Real estate.csv')
yt = df['Y house price of unit area'].values
xt = df.drop(df.columns[7], axis=1).values

class lreg():
    def __init__(self, xtrain, ytrain):
        self.xtrain = xtrain
        self.ytrain = ytrain

    def grad(self, w, b):
        a = self.xtrain
        c = self.ytrain
        m, n = a.shape
        djw = np.zeros(n)
        djb = 0
        for i in range(m):
            err = (np.dot(w, a[i]) + b) - c[i]
            for j in range(n):
                djw[j] = djw[j] + err * a[i, j]
            djb = djb + err
        djw = djw / m
        djb = djb / m
        return djw, djb

    def cost(self, w, b):
        a = self.xtrain
        c = self.ytrain
        m = a.shape[0]
        cost = 0.0
        for i in range(m):
            f_wb_i = np.dot(a[i], w) + b
            cost = cost + (f_wb_i - c[i]) ** 2
        cost = cost / (2 * m)
        return cost

    def gdesc(self, win, bin, cost, grad, iter, alpha):
        J_history = []
        w = copy.deepcopy(win)
        b = bin
        a = self.xtrain
        c = self.ytrain
        for i in range(iter):
            dj_dw, dj_db = grad(w, b)
            w = w - alpha * dj_dw
            b = b - alpha * dj_db
            if i < 100000:
                J_history.append(cost(w, b))
            if i % math.ceil(iter / 10) == 0:
                print(f"Iteration {i:4d}: Cost {J_history[-1]:8.2f}")
        return w, b, J_history

l1 = lreg(xt, yt)
# initialize parameters
initial_w = np.zeros_like(xt[0])
initial_b = 0.
# some gradient descent settings
iterations = 6000
alpha = 5.0e-10
# run gradient descent
w_final, b_final, J_hist = l1.gdesc(initial_w, initial_b, l1.cost, l1.grad, iterations, alpha)
print(f"b, w found by gradient descent: {b_final:0.2f}, {w_final} ")
for i in range(10):
    print(f"prediction: {np.dot(xt[i], w_final) + b_final:0.2f}, target value: {yt[i]}")


Iteration    0: Cost   810.19
Iteration  600: Cost   174.76
Iteration 1200: Cost   105.02
Iteration 1800: Cost    77.81
Iteration 2400: Cost    64.33
Iteration 3000: Cost    57.53
Iteration 3600: Cost    54.10
Iteration 4200: Cost    52.36
Iteration 4800: Cost    51.49
Iteration 5400: Cost    51.04
b, w found by gradient descent: 0.00, [ 2.04e-03  2.21e-02  1.01e-04 -6.75e-03  9.10e-05  2.74e-04  1.33e-03] 
prediction: 44.08, target value: 37.9
prediction: 42.59, target value: 42.2
prediction: 40.88, target value: 47.3
prediction: 40.88, target value: 54.8
prediction: 42.02, target value: 43.1
prediction: 29.98, target value: 32.1
prediction: 40.45, target value: 40.3
prediction: 42.74, target value: 46.7
prediction: 7.48, target value: 18.8
prediction: 32.65, target value: 22.1
